### ISSUE TITLE
Docker registration flow broken

### ISSUE THREAD

**Issue by vectorkovacspeter** [plausible/hosting#194]
After following the instructions in [readme](https://github.com/plausible/community-edition/blob/v2.1.4/README.md) file, the containers starts fine, but in the **Step 3 - Add site info** step the flow broken, and got a consol error message in the **plausible/community-edition:v2.1.4** container:
```console
2024-12-04 07:32:31 ** (exit) an exception was raised:
2024-12-04 07:32:31     ** (ArgumentError) The email address `plausible@localhost` is invalid.
2024-12-04 07:32:31 
2024-12-04 07:32:31         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:134: Mail.Renderers.RFC2822.validate_address/1
2024-12-04 07:32:31         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:141: Mail.Renderers.RFC2822.render_address/1
2024-12-04 07:32:31         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:97: Mail.Renderers.RFC2822.render_header/2
2024-12-04 07:32:31         (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
2024-12-04 07:32:31         (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
2024-12-04 07:32:31         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:174: Mail.Renderers.RFC2822.render_headers/2
2024-12-04 07:32:31         (mail 0.3.1) lib/mail/renderers/rfc_2822.ex:56: Mail.Renderers.RFC2822.render_part/2
2024-12-04 07:32:31         (bamboo_mua 0.2.2) lib/bamboo_mua.ex:57: Bamboo.Mua.deliver/2
```

**Steps to reproduce:**
Follow the steps 1 - 5 in the [readme](https://github.com/plausible/community-edition/blob/v2.1.4/README.md) file

probably needs to make som (or all) steps from the [email configuration](https://github.com/plausible/community-edition/wiki/configuration#email) docs, to solve this.
So its not a big deal, but the ones wants to try it out quickly its not a good fist plausible experience.

**Comment by ruslandoga** [comment]
👋 @vectorkovacspeter 

> Step 3 - Add site info

Do you mean the second step? Step 3 is about exposing HTTP ports.

**Comment by ruslandoga** [comment]
And regarding the error, I guess you used `BASE_URL=http://localhost:8000` or something like that?

We generate the mailer's email from `BASE_URL` if `MAILER_EMAIL` is not provided. There isn't much we can do if `BASE_URL` is set to something like `http://localhost:8000` and raising an exception as we do now seems good enough as it makes the user realize that something is wrong with their configuration. Note there would be no such error if `BASE_URL` is set to an actual domain name as the quick start suggests in step two :)

**Comment by ruslandoga** [comment]
We generate the mailer's email from BASE_URL if `MAILER_EMAIL` is not provided. There isn't much we can do if `BASE_URL=http://localhost:8000` and raising an exception as we do seems ot be good enough as you were able to see it and realize that something is wrong with your configuration.

**Comment by ruslandoga** [comment]
Ah, and https://github.com/plausible/community-edition/wiki/Configuration#enable_email_verification is set to `false` by default. So the registration emails are not sent out by default. Have you modified it?

Would you be able to share your configuration files and the steps you took to setup Plausible CE to better understand your issues?

**Comment by ruslandoga** [comment]
Would you be able to share your configuration files and the steps you took to setup Plausible CE to better understand your issues?
