### ISSUE TITLE
v1.5.0 release

### ISSUE THREAD

**Issue by ruslandoga** [plausible/hosting#54]
Going to track progress with this one. Here're the TODOs left.

#### Changes to docker compose config, in-repo upgrade docs

- [x] https://github.com/plausible/hosting/pull/52
- [x] add something like `upgrades/postgres.md` (naming is hard, suggestions are welcome) with the steps to upgrade postgres instances (more info in the PR above).

>  🙋‍♂️　Why not put it in the release notes on https://github.com/plausible/analytics/releases?
> 👩‍🏫　Because this guide is unlikely to change from release to release and we can link to that document on each update.

#### Changes to docs, manual tests

- [x] https://github.com/plausible/docs/pull/278
- [x] test CSV exporting, should work [as documented](https://plausible.io/docs/export-stats)

#### Changes to Plausible container image

- [x] https://github.com/plausible/analytics/pull/2103
- [x] https://github.com/plausible/analytics/pull/2214
- [x] https://github.com/plausible/analytics/pull/2250

**Comment by ruslandoga** [comment]
[`v1.5.0-rc.0`](https://github.com/plausible/analytics/discussions/2324) release candidate has been released.

**Comment by beykansen** [comment]
I am using the latest [docker image ](https://hub.docker.com/layers/plausible/analytics/latest/images/sha256-43a480f034e5abd7f60c4a05718707cc7f140b32cccad5ab868e2a23d46fd721?context=explore) (v1.5.0) but container instantly crashes after started.  I think invalid BUILD_METADATA causes this. FYI @ruslandoga 

This is not valid JSON:
```json
{
   "tags":[
      "plausible/analytics:v1.5.0",
      "plausible/analytics":v1.5,
      "plausible/analytics":v1,
      "plausible/analytics:latest"
   ],
   "labels":{
      "org.opencontainers.image.title":"analytics",
      "org.opencontainers.image.description":"Simple, open-source, lightweight (< 1 KB) and privacy-friendly web analytics alternative to Google Analytics.",
      "org.opencontainers.image.url":"https://github.com/plausible/analytics",
      "org.opencontainers.image.source":"https://github.com/plausible/analytics",
      "org.opencontainers.image.version":"v1.5.0",
      "org.opencontainers.image.created":"2022-12-02T15:45:09.831Z",
      "org.opencontainers.image.revision":"f9ab2650b3192021d5808cc8f20064aa8af543f4",
      "org.opencontainers.image.licenses":"AGPL-3.0"
   }
}
```

```
ERROR! Config provider Config.Reader failed with:

** (Jason.DecodeError) unexpected byte at position 38: 0x70 ("p")
    lib/jason.ex:92: Jason.decode!/2
    (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17.1) erl_eval.erl:446: :erl_eval.expr/5
    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
    (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
    (elixir 1.13.4) lib/config/reader.ex:92: Config.Reader.read!/2


{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Jason.DecodeError',data=><<"{\"tags\":[\"plausible/analytics:v1.5.0\",plausible/analytics:v1.5,plausible/analytics:v1,\"plausible/analytics:latest\"],\"labels\":{\"org.opencontainers.image.title\":\"analytics\",\"org.opencontainers.image.description\":\"Simple, open-source, lightweight (< 1 KB) and privacy-friendly web analytics alternative to Google Analytics.\",\"org.opencontainers.image.url\":\"https://github.com/plausible/analytics\",\"org.opencontainers.image.source\":\"https://github.com/plausible/analytics\",\"org.opencontainers.image.version\":\"v1.5.0\",\"org.opencontainers.image.created\":\"2022-12-02T15:45:09.831Z\",\"org.opencontainers.image.revision\":\"f9ab2650b3192021d5808cc8f20064aa8af543f4\",\"org.opencontainers.image.licenses\":\"AGPL-3.0\"}}">>,position=>38,token=>nil},[{'Elixir.Jason','decode!',2,[{file,"lib/jason.ex"},{line,92},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}

init terminating in do_boot ({,[{Elixir.Jason,decode!,2,[{_},{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by ruslandoga** [comment]
👋 @beykansen 

A quick fix is to set `BUILD_MATEDATA` to `{}` in `plausible-conf.env`

```diff
...
BASE_URL=replace-me
SECRET_KEY_BASE=replace-me
+ BUILD_METADATA={}
```

More info: https://github.com/plausible/analytics/issues/2491#issuecomment-1336014755

**Comment by ruslandoga** [comment]
@beykansen [`v1.5.1`](https://github.com/plausible/analytics/discussions/2507) has been released with a [fix.](https://github.com/plausible/analytics/pull/2503)

**Comment by productdevbook** [comment]
`sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run` dont working

**Comment by productdevbook** [comment]
```
** (UndefinedFunctionError) function :nxdomain.exception/1 is undefined (module :nxdomain is not available)
    :nxdomain.exception([])
    (db_connection 2.4.2) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
```

**Comment by ruslandoga** [comment]
👋 @productdevbook

It seems like clickhouse hostname is invalid. Can you please share more of your setup?

**Comment by productdevbook** [comment]
yes thats true fixed thank you
